<?xml version="1.0" encoding="UTF-8"?>

<!--
 * See the NOTICE file distributed with this work for additional
 * information regarding copyright ownership.
 *
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
-->

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.xwiki.contrib</groupId>
        <artifactId>parent-platform</artifactId>
        <version>8.4-16</version>
    </parent>
    <artifactId>pamauth-authenticator</artifactId>
    <version>1.0.2-SNAPSHOT</version>
    <packaging>jar</packaging>
    <name>PAM Authentication</name>
    <description>Password Authentication Module (PAM) bridge</description>
    <url>https://github.com/xwiki-contrib/authenticator-pam</url>

    <scm>
        <connection>scm:git:git://github.com/xwiki-contrib/authenticator-pam.git</connection>
        <developerConnection>scm:git:git@github.com:xwiki-contrib/authenticator-pam.git</developerConnection>
        <url>https://github.com/xwiki-contrib/authenticator-pam</url>
        <tag>HEAD</tag>
    </scm>

    <developers>
	<developer>
	    <name>Paul Landes</name>
            <url>http://github.com/plandes</url>
	</developer>
    </developers>

    <properties>
        <xwiki.jacoco.instructionRatio>0.00</xwiki.jacoco.instructionRatio>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.site.readme.dir>${basedir}/src/site/markdown</project.site.readme.dir>
        <xwiki.revapi.skip>true</xwiki.revapi.skip>
        <xwiki.extension.name>PAM Authenticator</xwiki.extension.name>
        <xwiki.extension.category>api</xwiki.extension.category>
        <xwiki.release.jira.skip>false</xwiki.release.jira.skip>
        <xwiki.issueManagement.jira.id>PAMAUTH</xwiki.issueManagement.jira.id>
        <xwiki.checkstyle.skip>true</xwiki.checkstyle.skip>
    </properties>

    <dependencies>
        <!-- xwiki -->
        <dependency>
            <groupId>javax.servlet</groupId>
            <artifactId>javax.servlet-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.xwiki.platform</groupId>
            <artifactId>xwiki-platform-oldcore</artifactId>
            <version>${platform.version}</version>
        </dependency>
        <!-- Remove when upgrading to XWiki 13.3+ -->
        <dependency>
            <groupId>org.xwiki.contrib</groupId>
            <artifactId>userauthenticatedevent-backport</artifactId>
            <version>1.0.0</version>
        </dependency>

        <!-- pwauth wrapper -->
        <dependency>
            <groupId>com.zensols.sys</groupId>
            <artifactId>userauth</artifactId>
            <version>0.0.1</version>
        </dependency>

        <!-- xwiki testing -->
        <dependency>
            <groupId>org.xwiki.commons</groupId>
            <artifactId>xwiki-commons-tool-test-component</artifactId>
            <version>${commons.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.xwiki.platform</groupId>
            <artifactId>xwiki-platform-oldcore</artifactId>
            <version>${platform.version}</version>
            <type>test-jar</type>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <reporting>
	<plugins>
            <!-- nail down the site phase plugin -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-project-info-reports-plugin</artifactId>
                <version>3.9.0</version>
            </plugin>

            <!-- javadoc -->
	    <plugin>
		<groupId>org.apache.maven.plugins</groupId>
		<artifactId>maven-javadoc-plugin</artifactId>
                <version>2.10.4</version>
            </plugin>
        </plugins>
    </reporting>

    <build>
        <plugins>
            <!-- attach javadocs -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-javadoc-plugin</artifactId>
                <version>2.9.1</version>
                <executions>
                    <execution>
                        <id>attach-javadocs</id>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <!-- sign artifacts -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-gpg-plugin</artifactId>
                <version>1.6</version>
                <executions>
                    <execution>
                        <id>sign-artifacts</id>
                        <phase>package</phase>
                        <goals>
                            <goal>sign</goal>
                        </goals>
                        <configuration>
                            <keyname>${gpg.keyname}</keyname>
                            <passphraseServerId>${gpg.keyname}</passphraseServerId>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <!-- use README.md in maven site -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-resources-plugin</artifactId>
                <version>3.0.1</version>
                <executions>
                    <execution>
                        <!-- Copy the readme file to the site source files so that a page is generated from it. -->
                        <id>copy-readme</id>
                        <phase>pre-site</phase>
                        <goals>
                            <goal>copy-resources</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${project.site.readme.dir}</outputDirectory>
                            <resources>
                                <resource>
                                    <directory>${basedir}</directory>
                                    <includes>
                                        <include>README.md</include>
                                    </includes>
                                </resource>
                            </resources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <!-- clean copied README.md used in maven site build -->
            <plugin>
                <artifactId>maven-clean-plugin</artifactId>
                <version>3.0.0</version>
                <configuration>
                    <filesets>
                        <fileset>
                            <directory>${project.site.readme.dir}</directory>
                            <followSymlinks>false</followSymlinks>
                        </fileset>
                    </filesets>
                </configuration>
            </plugin>

            <!-- generate GitHub Pages for site -->
            <plugin>
                <groupId>com.github.github</groupId>
                <artifactId>site-maven-plugin</artifactId>
                <version>0.12</version>
                <configuration>
                    <message>Creating site for ${project.version}</message>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>site</goal>
                        </goals>
                        <phase>site</phase>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
